// Fotografie-Daten für die Galerie. Kategorien: portrait, natur, architektur, tiere, momente
const PHOTOS = [
  { slug: "nebelmeer-gold", category: "natur", title: "Nebelmeer in Gold", alt: "Drohnenperspektive über einem goldenen Nebelmeer bei Sonnenaufgang", ratio: 1.4989 },
  { slug: "bridge-fog", category: "architektur", title: "Stahlbrücke im Morgennebel", alt: "Stahlfachwerkbrücke, die im dichten Morgennebel verschwindet", ratio: 1.4989 },
  { slug: "portrait-timo-drone", category: "portrait", title: "Timo mit der Drohne", alt: "Portrait eines jungen Mannes mit Drohne in der Hand vor Bergpanorama", ratio: 0.6671 },
  { slug: "lake-fog-gold", category: "natur", title: "Goldener Nebel am Ufer", alt: "Baum am Seeufer im goldenen Morgennebel", ratio: 1.4989 },
  { slug: "portrait-jump-bw", category: "portrait", title: "Bewegung im Gegenlicht", alt: "Schwarz-weiß Portrait einer springenden Person im Gegenlicht", ratio: 0.6671 },
  { slug: "church-tower-street", category: "architektur", title: "Kirchturm über der Altstadt", alt: "Barocker Kirchturm zwischen Altstadthäusern", ratio: 0.6671 },
  { slug: "cat-tongue", category: "tiere", title: "Katze im Abendlicht", alt: "Nahaufnahme einer Katze im Gras", ratio: 1.4989 },
  { slug: "bridge-sunset-flare", category: "natur", title: "Gegenlicht an der Bahnbrücke", alt: "Sonne blendet hinter einer Eisenbahnbrücke", ratio: 1.4989 },
  { slug: "portrait-sophia", category: "portrait", title: "Sophia", alt: "Portrait von Sophia mit Brille, lachend", ratio: 1.4989 },
  { slug: "architecture-corner-lamp", category: "architektur", title: "Gassenlaterne", alt: "Laterne an einer Hausecke, Blick von unten", ratio: 0.6671 },
  { slug: "ant-macro", category: "natur", title: "Ameise am Zweig", alt: "Makroaufnahme einer Ameise, die an einem Zweig hängt", ratio: 1.4989 },
  { slug: "portrait-two-snow", category: "portrait", title: "Winterwandern im Schnee", alt: "Zwei Personen mit Wintermützen im verschneiten Wald", ratio: 1.4989 },
  { slug: "dog-portrait", category: "tiere", title: "Hundeblick", alt: "Nahaufnahme eines Hundes, direkter Blickkontakt", ratio: 0.6671 },
  { slug: "church-tower-tree", category: "architektur", title: "Kirchturm im Abendlicht", alt: "Kirchturm hinter herbstlichem Baum", ratio: 0.6671 },
  { slug: "portrait-couple-field", category: "portrait", title: "Paar im Abendlicht", alt: "Elegant gekleidetes Paar hält Hände auf einer Blumenwiese", ratio: 0.6671 },
  { slug: "lake-fog-blue", category: "natur", title: "Nebel über dem See", alt: "Spiegelung eines Baumes im nebligen See", ratio: 1.4989 },
  { slug: "cat-walking", category: "tiere", title: "Nächtlicher Streuner", alt: "Katze läuft nachts auf einen Weg zu", ratio: 0.6414 },
  { slug: "architecture-facade-sky", category: "architektur", title: "Fassade gegen Himmel", alt: "Gebäudekante vor bewölktem Himmel, Froschperspektive", ratio: 0.6671 },
  { slug: "bridge-sunset-tree", category: "natur", title: "Baumsilhouette an der Brücke", alt: "Baumsilhouette vor Brücke im Sonnenuntergang", ratio: 1.4989 },
  { slug: "sport-football", category: "momente", title: "Spielpause", alt: "American-Football-Spieler kniet auf dem Feld", ratio: 1.4989 },
  { slug: "cat-peek", category: "tiere", title: "Neugieriger Blick", alt: "Katze schaut neugierig hinter einem Holzpfosten hervor", ratio: 1.4989 },
  { slug: "architecture-underpass", category: "architektur", title: "Perspektive von unten", alt: "Architektonische Struktur von unten fotografiert", ratio: 1.4989 },
  { slug: "mountains-panorama", category: "natur", title: "Alpenpanorama", alt: "Weites Bergpanorama im Abendlicht", ratio: 1.3333 },
  { slug: "portrait-paul", category: "portrait", title: "Paul", alt: "Portrait von Paul, der in eine Erdbeere beißt", ratio: 0.6657 },
  { slug: "foggy-night-lights", category: "natur", title: "Nebliger Platz bei Nacht", alt: "Lichter spiegeln sich nachts im Nebel auf nasser Fläche", ratio: 1.6548 },
  { slug: "event-red-light", category: "momente", title: "Konzertlicht in Rot", alt: "Kirchenraum in dramatisches rotes Licht getaucht", ratio: 1.4989 },
  { slug: "portrait-robin", category: "portrait", title: "Robin", alt: "Portrait von Robin vor dunklem Hintergrund", ratio: 0.6829 },
  { slug: "product-drone-mower", category: "momente", title: "Technik im Feld", alt: "Technisches Gerät auf einer Wiese bei Sonnenuntergang", ratio: 1.4989 },
  { slug: "chainsaw-still", category: "momente", title: "Motorsäge im Moos", alt: "Motorsäge liegt auf moosbewachsenem Waldboden", ratio: 1.4989 },
  { slug: "architecture-cctv", category: "architektur", title: "Überwachung", alt: "Überwachungskamera an einer Hausecke im Licht", ratio: 0.6671 },
];
